FROM ruby:3.1.2 as bundle

ARG PACKAGES_TOKEN

ENV RAILS_LOG_TO_STDOUT=1

COPY Gemfile Gemfile.lock /app/

WORKDIR /app

RUN gem install bundler -v 2.3.12 && \
    gem cleanup bundler

# second stage
FROM ruby:3.1.2
ENV LANG C.UTF-8

RUN apt-get update &&\
    apt-get install -y \
    netcat

COPY --from=bundle ${GEM_HOME} ${GEM_HOME}
WORKDIR /app

COPY docker-entrypoint-dev.sh /

ENTRYPOINT ["/./docker-entrypoint-dev.sh"]
