version: '3'
services:
 db:
  image: postgres:13.1-alpine
  container_name: garden-of-intelligence-db
  restart: always
  environment:
    - POSTGRES_PASSWORD=postgres
  volumes:
   - ./tmp/postgres/data:/var/lib/postgresql/data
  ports:
   - "${DOCKER_POSTGRES_PORT-5432}:5432"
  
 app:
  container_name: garden-of-intelligence-app
  build:
    context: .
    dockerfile: ./Dockerfile.development
  environment:
      - DATABASE_URL
  volumes:
    - .:/app
    - /app/tmp # don't mount tmp directory
  ports:
   - "3000:3000"
  tty: true
  stdin_open: true