default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: garden-of-intelligence
  password: <%= ENV['GARDEN_OF_INTELLIGENCE_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: garden-of-intelligence_development

test:
  <<: *default
  database: garden-of-intelligence_test

production:
  <<: *default
  url: <%= ENV.fetch('DATABASE_URL', '') %>

