default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  url: <%= ENV.fetch('DATABASE_URL', 'postgresql://postgres:postgres@garden-of-intelligence-db:5432/garden-of-intelligence-db_development') %>

test:
  <<: *default
  url: <%= ENV.fetch('TEST_DATABASE_URL', 'postgresql://postgres:postgres@garden-of-intelligence-db:5432/garden-of-intelligence-db_test') %>

production:
  <<: *default
  database: garden-of-intelligence
  url: <%= ENV['DATABASE_URL'] %>
