name: Dependabot auto-merge

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed
  pull_request:
    types:
      - opened
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot_auto_merge:
    runs-on: ubuntu-latest
     # Only for workflows initiated by Dependabot
    if: ${{ github.actor == 'dependabot[bot]' }}

    steps:
      - name: automerge
        uses: pascalgn/automerge-action@v0.14.3 # https://github.com/pascalgn/automerge-action
        env:
          MERGE_LABELS: '' # all
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: squash
